# Site settings
title: Dean Rather's Blog
description: > # this means to ignore newlines until "baseurl:"
  Dean's blog.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://blog.deanrather.com"

# Build settings
markdown: kramdown
paginate: 5 # pagination based on number of posts
paginate_path: "page/:num"
highlighter: pygments
gems: [jekyll-paginate, jekyll-coffeescript]

# comments
disqus: # add disqus shortname here

# author info
# add your appropriate info here
author: Dean Rather
bio:    # your bio
email:
email_md5: # md5 hash of your email
twitter_username: deanrather
github_username: deanrather

# Theming options
# These settings are mandatory.
theme:              'blue-pink'
# drawer theming
drawer:
  text_color:       'grey-600'
  header_color:     'blue-500'
  navigation_color: 'grey-200'
# footer theming
footer:
  text_color: 'blue-grey-200'
  color: 'blue-grey-600'
